### ISSUE TITLE
Video?

### ISSUE THREAD

**Issue by tobsecret** [ioam/scipy-2017-holoviews-tutorial#13]
Is the video for this tutorial going to be uploaded? I cannot seem to find it on the enthought youtube channel.

**Comment by jlstevens** [comment]
We received an e-mail from the SciPy organizers informing us that there were issues with the audio - apparently some construction noises got picked up in that conference room. Last we heard, they are trying to clear up the audio and will get back in touch once they have cleaned up the audio as much as they can.

As soon as the video is online, I'll paste the link into this issue.

**Comment by j-phi** [comment]
I was linked here by the [video on YouTube](https://www.youtube.com/watch?v=cMXKE0nB8k4&list=PLYx7XA2nY5GfdAFycPLBdUDOUtdQIVoMf&index=29); is this what you were looking for?

**Comment by tobsecret** [comment]
Yes, thanks! that's what I was looking for!
